// Categories of suggestions
const suggestions = {
  sports: [
    "Who won the IPL 2024?",
    "ICC World Cup 2023 final score",
    "Messi vs Ronaldo stats comparison",
    "Most goals in FIFA history",
    "NBA top scorers 2024",
    "India vs Pakistan next match date",
    "Fastest bowler in cricket",
    "Most sixes in IPL history",
    "Highest run scorer in ODI",
    "LeBron James career points",
    "Who will win Euro 2024?",
    "Fastest century in T20",
    "Tennis Grand Slam winners 2024",
    "Wimbledon 2024 schedule",
    "Top 10 football players 2025",
    "Formula 1 2024 standings",
    "Cricket World Cup venues 2023",
    "India Olympic medals 2024",
    "Kabaddi Pro League 2025 updates",
    "What is VAR in football?",
    "Lionel Messi net worth 2025",
    "BCCI upcoming matches",
    "Who holds the most gold medals in Olympics?",
    "IPL auction highest bid 2024",
    "Women's T20 World Cup winner",
    "CSK team 2024 players",
    "Who is No.1 in Test ranking?",
    "Who is Orange Cap holder 2024?",
    "Fastest 100m sprinter 2025",
    "Who is the best goalkeeper in 2024?",
    "Copa America winners list",
    "World Cup 2026 host country",
    "Which team won the most Champions League titles?",
    "India's football team FIFA ranking",
    "Cricket rules and basics",
    "Tokyo Olympics record holders",
    "What is Duckworth Lewis method?",
    "Who is the next cricket captain?",
    "Live football match score today",
    "Badminton ranking 2025",
    "Who is the GOAT in basketball?",
    "Most valuable football clubs 2025",
    "Boxing heavyweight champion 2025",
    "Who has the most wickets in IPL?",
    "When is the next IPL mega auction?",
    "Asian Games India medal tally",
    "Which cricketer has the most followers on Instagram?",
    "Who is the youngest F1 winner?",
    "Who won the UEFA Champions League 2024?",
    "What are the new cricket rules for 2025?",
    "What is the highest partnership in ODI cricket?",
    "Who scored the most runs in Test cricket history?",
    "How does the DRS system work in cricket?",
    "What is a super over in cricket?",
    "Who bowled the most dot balls in T20 history?",
    "What is powerplay in cricket?",
    "What is the difference between ODI and T20?",
    "Who is the best all-rounder in the world?",
    "Which team has won the most IPL trophies?",
    "What are the top 10 bowling figures in Test cricket?",
    "How many World Cups has India won?",
    "Who hit six sixes in an over in international cricket?",
    "What is the role of a third umpire?",
    "What is impact player rule in IPL?",
    "Which bowler has the most hat-tricks in IPL?",
    "What are the ICC future tours for India?",
    "Who is the most expensive player in PSL?",
    "What is the Mankading rule in cricket?",
    "What is the slowest century in Test cricket?",
    "Who has the most stumpings in international cricket?",
    "Who is the top scorer in Premier League history?",
    "What are the rules of offside in football?",
    "What is the Golden Boot in FIFA?",
    "What is the Ballon d'Or and who won it in 2024?",
    "What is the UEFA Nations League?",
    "Who is the youngest football player to debut in World Cup?",
    "What is the meaning of aggregate score in football?",
    "How does VAR work in football?",
    "Which football clubs have the most fans?",
    "What is a hat-trick in football?",
    "Who are the top 5 football managers of all time?",
    "What are the most expensive football transfers in 2024?",
    "How many Champions League titles does Real Madrid have?",
    "Who are the top assist providers in football?",
    "Which country has won the most FIFA World Cups?",
    "Who is the richest footballer in the world?",
    "What is the history of El Clasico?",
    "Who are the top scorers in UEFA Euro history?",
    "What is the format of Copa America 2024?",
    "Who has the most clean sheets in football?",
    "What is a triple-double in NBA?",
    "Who has the most NBA MVP titles?",
    "How many championships has Michael Jordan won?",
    "What is the salary cap in NBA?",
    "Who are the top 10 NBA players of all time?",
    "What is the NBA draft process?",
    "What is a buzzer beater in basketball?",
    "What is the average height of an NBA player?",
    "Who is the youngest NBA All-Star?",
    "What are the NBA playoff brackets 2025?",
    "Who has the most Grand Slam titles in tennis?",
    "What is a walkover in tennis?",
    "How does the ATP ranking system work?",
    "What is the difference between ATP and WTA?",
    "Who are the top 10 female tennis players in 2025?",
    "What is a tie-break in tennis?",
    "How many sets are played in Grand Slam finals?",
    "What is the prize money for Wimbledon 2024?",
    "Who has the fastest serve in tennis history?",
    "What surface is the French Open played on?",
    "What is DRS in Formula 1?",
    "Who has the most pole positions in F1 history?",
    "What are the F1 teams and drivers for 2025?",
    "What is the F1 sprint race format?",
    "How does the F1 point system work?",
    "What is the fastest lap in F1 history?",
    "Who are the top 5 F1 drivers of all time?",
    "How many world titles does Lewis Hamilton have?",
    "What is a pit stop strategy in F1?",
    "Who won the Monaco Grand Prix 2024?",
    "Who is the world No.1 in badminton 2025?",
    "What are the basic rules of badminton?",
    "What is the difference between singles and doubles in badminton?",
    "Who won the All England Badminton Championship 2024?",
    "What is the scoring system in badminton?",
    "Who has the most Super Series titles in badminton?",
    "What are the top tournaments in badminton?",
    "How long is a badminton match on average?",
    "Who are the top 10 male badminton players?",
    "Which country dominates badminton world rankings?",
    "Who is the UFC lightweight champion 2025?",
    "What is the difference between boxing and MMA?",
    "Who is the best pound-for-pound boxer?",
    "What is a KO and TKO in boxing?",
    "Who has the fastest knockout in MMA history?",
    "What are the top UFC fights of all time?",
    "What is the meaning of reach in boxing?",
    "Who is the current heavyweight boxing champion?",
    "What is the history of Conor McGregor's career?",
    "What are weight classes in MMA?",
    "Who won the Masters 2024?",
    "What are the four major golf tournaments?",
    "What is a birdie, eagle, and bogey in golf?",
    "Who is the top-ranked golfer in 2025?",
    "What is the average length of a golf course?",
    "Who is the richest golfer in history?",
    "How is golf scored?",
    "What is the Ryder Cup?",
    "Who has the most PGA Tour wins?",
    "What is the FedEx Cup?",
    "Who won the Hockey World Cup 2023?",
    "What are the basic rules of field hockey?",
    "Who is the best goalkeeper in hockey?",
    "How many players are on a hockey team?",
    "What is the penalty shoot-out rule in hockey?",
    "What is the scoring system in volleyball?",
    "Who is the best volleyball player in the world?",
    "What are the top international volleyball tournaments?",
    "How many players are on a volleyball team?",
    "What is a libero in volleyball?",
    "What is the 100m world record?",
    "Who won the men's marathon at Olympics 2024?",
    "What are the decathlon events?",
    "Who is the fastest woman in the world 2025?",
    "What is a false start in sprinting?",
    "When are the next Olympic Games?",
    "What is the medal tally of USA in Olympics 2024?",
    "What are the new sports added to Olympics 2024?",
    "Who was the flag bearer for India in 2024?",
    "What is the meaning of Olympic rings?",
    "Best fantasy cricket team for today?",
    "Top football fantasy league picks this week?",
    "Where to watch live football matches for free?",
    "What are the top fantasy sports apps in 2025?",
    "How to calculate fantasy points in cricket?",
    "Who is the captain of Real Madrid in 2025?",
    "Who is the coach of Indian cricket team 2025?",
    "What is the playing 11 for today's match?",
    "Which clubs qualified for UCL 2025?",
    "Who is the vice captain of Team India?",
    "What is esports?",
    "Which countries play kabaddi?",
    "What is the history of the Ashes series?",
    "What are the top stadiums in the world?",
    "What is the oldest sports tournament?",
    "Who has the most assists in NBA history?",
    "Who has the highest batting average in Test cricket?",
    "Which footballer has played the most matches?",
    "Who has the most red cards in football?",
    "Who scored the fastest goal in football history?",
    "What is LBW in cricket?",
    "How is offside different from obstruction in hockey?",
    "What is a free kick in football?",
    "What is a no-ball in cricket?",
    "What is a technical foul in basketball?",
    "Who won the Ashes 2023?",
    "How many goals has Neymar scored for Brazil?",
    "What is the longest tennis match ever played?",
    "Who is the shortest NBA player of all time?",
    "What is a grand slam in baseball?",
    "What is the history of the Boston Marathon?",
    "What is the record for most goals in a single World Cup match?",
    "What is a googly in cricket?",
    "What are the dimensions of a football field?",
    "What is the use of hawk-eye in sports?",
    "What are the best free sports streaming apps?",
    "What is a double fault in tennis?",
    "What are the top 10 fastest F1 cars ever?",
    "What is a wet race in Formula 1?",
    "How are Olympic athletes selected?",
    "What is the most-watched sports event in the world?",
    "Who has won the most UFC fights?",
    "What is the most expensive sports trophy?",
    "What is the history of kabaddi in India?",
    "Who invented basketball?",
    "What are the major cycling events worldwide?",
    "Who has the most wins in MotoGP?",
    "How many medals has India won in Paralympics?",
    "Who is the best freestyle wrestler currently?",
    "What is a power play in hockey?",
    "What is the standard weight of a cricket ball?",
    "How long is a marathon?",
    "Who is the best sports commentator?",
    "What is the format of the NFL playoffs?",
    "What is the most points scored in a basketball game by one player?",
    "What is the salary of top cricketers in India?",
    "What is the origin of rugby?",
    "Who won the World Chess Championship 2024?",
    "What is the average time for a pit stop in F1?",
    "What is VAR and when was it introduced?",
    "What is the penalty rule in football?",
    "How is net run rate calculated in cricket?",
    "What is the record for most gold medals in a single Olympics?",
    "What is the structure of IPL 2025?",
    "How many rounds are there in a boxing match?",
    "Who is the top scorer in international hockey?",
    "What is a by-run in cricket?",
    "What is the most common injury in football?",
    "Who holds the world record in high jump?",
    "What are the rules for super tie-break in tennis?",
    "What is the difference between Test and First-Class cricket?",
    "What is the red card rule in football?",
    "Who is the youngest Olympic medalist ever?",
    "How do sports rankings work?",
    "What is a slam dunk in basketball?",
    "What are the rules for substitution in volleyball?",
    "Who is the current kabaddi world champion?",
    "What is a balk in baseball?",
    "What is the average career length of a footballer?",
    "Who holds the most records in sports history?"
  ],
  actors: [
    "Top 10 Bollywood actors 2025",
    "Hollywood actors in Marvel movies",
    "South Indian actors with most fans",
    "Most paid actress in the world",
    "Upcoming movies of Salman Khan",
    "Priyanka Chopra latest project",
    "Tom Holland new movie 2025",
    "Highest paid actors in Tollywood",
    "Shahrukh Khan net worth 2025",
    "Who is the best actor in India?",
    "Leonardo DiCaprio Oscar wins",
    "K-drama actors to watch in 2025",
    "Popular web series actors 2025",
    "Alia Bhatt awards list",
    "Who is the most versatile actor?",
    "Allu Arjun next movie name",
    "Robert Downey Jr filmography",
    "Who is the youngest Bollywood actor?",
    "Netflix top actors today",
    "Popular Kannada actors 2025",
    "Vijay Sethupathi best movies",
    "Most followed actors on Instagram",
    "Ranveer Singh transformation photos",
    "Who are the Avengers cast?",
    "Best actress in Tamil cinema",
    "Johnny Depp latest news",
    "Rajinikanth box office records",
    "Top 5 Malayalam actors 2025",
    "Who is the next James Bond?",
    "Indian actors in Hollywood",
    "Most stylish actors in India",
    "Who has the most Filmfare awards?",
    "Samantha Ruth Prabhu next movie",
    "Favorite actor in youth poll 2025",
    "Anushka Sharma comeback movie",
    "Top 10 actors by IMDb rating",
    "Who won Best Actor Oscar 2024?",
    "Which actor has the most fans worldwide?",
    "Movie actors turned producers",
    "Best newcomers in 2025",
    "Most powerful actor couples",
    "Kamal Haasan filmography",
    "Dhanush upcoming Hollywood projects",
    "Most iconic villain roles",
    "Famous voice-over artists in India",
    "Debut films of Bollywood stars",
    "Who is doing KGF 3?",
    "Latest rumors in Tollywood",
    "Who is playing Ram in Ramayana 2025?",
    "Highest grossing actors 2025",
    "Who is the highest-paid actor in 2025?",
    "What are the upcoming movies of Chris Hemsworth?",
    "How many Oscars has Leonardo DiCaprio won?",
    "What is the net worth of Tom Holland?",
    "Who is the most followed actor on Instagram?",
    "Which actor played the Joker in the latest Batman movie?",
    "What is the age of Zendaya?",
    "Who are the top 10 Bollywood actors in 2025?",
    "What is the latest movie of Dwayne Johnson?",
    "Who is the best actor in Hollywood?",
    "What are the top movies of Robert Downey Jr.?",
    "Who is the youngest Oscar-winning actor?",
    "What is the height of Chris Evans?",
    "Who played Iron Man in Marvel movies?",
    "What is the real name of The Rock?",
    "Who is the richest actor in the world?",
    "What are the upcoming projects of Scarlett Johansson?",
    "Who won the Best Actor award at the 2025 Oscars?",
    "What is the latest news about Johnny Depp?",
    "Who is the most versatile actor in Hollywood?",
    "What are the top movies of Brad Pitt?",
    "Who is the most popular South Indian actor?",
    "What is the latest movie of Emma Watson?",
    "Who are the Avengers cast members?",
    "What is the age of Ryan Reynolds?",
    "Who played Spider-Man in the latest Marvel movies?",
    "What is the net worth of Salman Khan?",
    "Who is the best actress in Bollywood?",
    "What are the top movies of Tom Cruise?",
    "Who is the most stylish actor in India?",
    "What is the latest project of Priyanka Chopra?",
    "Who is the most followed actress on Instagram?",
    "What is the age of Jennifer Lawrence?",
    "Who played Captain America in Marvel movies?",
    "What is the real name of Shah Rukh Khan?",
    "Who is the richest actress in the world?",
    "What are the upcoming movies of Deepika Padukone?",
    "Who won the Best Actress award at the 2025 Oscars?",
    "What is the latest news about Angelina Jolie?",
    "Who is the most versatile actress in Hollywood?",
    "What are the top movies of Meryl Streep?",
    "Who is the most popular Tollywood actor?",
    "What is the latest movie of Alia Bhatt?",
    "Who are the Justice League cast members?",
    "What is the age of Chris Pratt?",
    "Who played Thor in Marvel movies?",
    "What is the net worth of Akshay Kumar?",
    "Who is the best actor in Tamil cinema?",
    "What are the top movies of Hugh Jackman?",
    "Who is the most stylish actress in India?",
    "What is the latest project of Anushka Sharma?",
    "Who is the most followed male actor on Twitter?",
    "What is the age of Emma Stone?",
    "Who played Black Widow in Marvel movies?",
    "What is the real name of Rajinikanth?",
    "Who is the richest male actor in Bollywood?",
    "What are the upcoming movies of Kareena Kapoor?",
    "Who won the Best Supporting Actor award at the 2025 Oscars?",
    "What is the latest news about Natalie Portman?",
    "Who is the most versatile actor in Tollywood?",
    "What are the top movies of Benedict Cumberbatch?",
    "Who is the most popular Kannada actor?",
    "What is the latest movie of Kangana Ranaut?",
    "Who are the X-Men cast members?",
    "What is the age of Henry Cavill?",
    "Who played Superman in the latest DC movies?",
    "What is the net worth of Aamir Khan?",
    "Who is the best actress in Tamil cinema?",
    "What are the top movies of Christian Bale?",
    "Who is the most stylish male actor in Hollywood?",
    "What is the latest project of Taapsee Pannu?",
    "Who is the most followed female actor on Facebook?",
    "What is the age of Margot Robbie?",
    "Who played Wonder Woman in DC movies?",
    "What is the real name of Chiranjeevi?",
    "Who is the richest female actor in Bollywood?",
    "What are the upcoming movies of Katrina Kaif?",
    "Who won the Best Supporting Actress award at the 2025 Oscars?",
    "What is the latest news about Reese Witherspoon?",
    "Who is the most versatile actress in Tollywood?",
    "What are the top movies of Joaquin Phoenix?",
    "Who is the most popular Malayalam actor?",
    "What is the latest movie of Parineeti Chopra?",
    "Who are the Fantastic Four cast members?",
    "What is the age of Jason Momoa?",
    "Who played Aquaman in DC movies?",
    "What is the net worth of Hrithik Roshan?",
    "Who is the best actor in Malayalam cinema?",
    "What are the top movies of Matt Damon?",
    "Who is the most stylish actress in Hollywood?",
    "What is the latest project of Shraddha Kapoor?",
    "Who is the most followed male actor on Instagram?",
    "What is the age of Brie Larson?",
    "Who played Captain Marvel in Marvel movies?",
    "What is the real name of Mahesh Babu?",
    "Who is the richest male actor in Tollywood?",
    "What are the upcoming movies of Sonam Kapoor?",
    "Who won the Best Actor award at the 2025 Golden Globes?",
    "What is the latest news about Anne Hathaway?",
    "Who is the most versatile actor in Malayalam cinema?",
    "What are the top movies of Ryan Gosling?",
    "Who is the most popular Bengali actor?",
    "What is the latest movie of Kriti Sanon?",
    "Who are the Guardians of the Galaxy cast members?",
    "What is the age of Benedict Wong?",
    "Who played Doctor Strange in Marvel movies?",
    "What is the net worth of Ranbir Kapoor?",
    "Who is the best actress in Malayalam cinema?",
    "What are the top movies of Jake Gyllenhaal?",
    "Who is the most stylish male actor in Bollywood?",
    "What is the latest project of Bhumi Pednekar?",
    "Who is the most followed female actor on Twitter?",
    "What is the age of Gal Gadot?",
    "Who played Batman in the latest DC movies?",
    "What is the real name of Dhanush?",
    "Who is the richest female actor in Tollywood?",
    "What are the upcoming movies of Yami Gautam?",
    "Who won the Best Actress award at the 2025 Golden Globes?",
    "What is the latest news about Jennifer Aniston?",
    "Who is the most versatile actress in Malayalam cinema?",
    "What are the top movies of Michael B. Jordan?",
    "Who is the most popular Marathi actor?",
    "What is the latest movie of Radhika Apte?",
    "Who are the Suicide Squad cast members?",
    "What is the age of Ezra Miller?",
    "Who played The Flash in DC movies?",
    "What is the net worth of Ajay Devgn?",
    "Who is the best actor in Bengali cinema?",
    "What are the top movies of Daniel Radcliffe?",
    "Who is the most stylish actress in Tollywood?",
    "What is the latest project of Huma Qureshi?",
    "Who is the most followed male actor on Facebook?",
    "What is the age of Florence Pugh?",
    "Who played Hawkeye in Marvel movies?",
    "What is the real name of Nani?",
    "Who is the richest male actor in Malayalam cinema?",
    "What are the upcoming movies of Ileana D'Cruz?",
    "Who won the Best Supporting Actor award at the 2025 Golden Globes?",
    "What is the latest news about Sandra Bullock?",
    "Who is the most versatile actor in Bengali cinema?",
    "What are the top movies of Tom Hanks?",
    "Who is the most popular Punjabi actor?",
    "What is the latest movie of Vidya Balan?",
    "Who are the Eternals cast members?",
    "What is the age of Richard Madden?",
    "Who played Ikaris in Marvel movies?",
    "What is the net worth of Saif Ali Khan?",
    "Who is the best actress in Bengali cinema?",
    "What are the top movies of Will Smith?",
    "Who is the most stylish male actor in Tollywood?",
    "What is the latest project of Richa Chadha?",
    "Who is the most followed female actor on YouTube?",
    "What is the age of Sophie Turner?",
    "Who played Jean Grey in X-Men movies?",
    "What is the real name of Mammootty?",
    "Who is the richest female actor in Malayalam cinema?",
    "What are the upcoming movies of Nargis Fakhri?",
    "Who won the Best Supporting Actress award at the 2025 Golden Globes?",
    "What is the latest news about Julia Roberts?",
    "Who is the most versatile actress in Bengali cinema?",
    "What are the top movies of Keanu Reeves?",
    "Who is the most popular Bhojpuri actor?",
    "What is the latest movie of Tabu?",
    "Who are the Shazam! cast members?",
    "What is the age of Zachary Levi?",
    "Who played Shazam in DC movies?",
    "What is the net worth of Anil Kapoor?",
    "Who is the best actor in Punjabi cinema?",
    "What are the top movies of Edward Norton?",
    "Who is the most stylish actress in Bengali cinema?",
    "What is the latest project of Rani Mukerji?",
    "Who is the most followed male actor on TikTok?",
    "What is the age of Lily Collins?",
    "Who played Scarlet Witch in Marvel movies?",
    "What is the real name of Mohanlal?",
    "Who is the richest male actor in Bengali cinema?",
    "What are the upcoming movies of Jacqueline Fernandez?",
    "Who won the Best Actor award at the 2025 BAFTA Awards?",
    "What is the latest news about Nicole Kidman?",
    "Who is the most versatile actor in Bhojpuri cinema?",
    "What are the top movies of Mark Ruffalo?",
    "Who is the most popular Assamese actor?",
    "What is the latest movie of Sushmita Sen?",
    "Who are the Deadpool cast members?",
    "What is the age of Ryan Reynolds?",
    "Who played Deadpool in Marvel movies?",
    "What is the net worth of Varun Dhawan?",
    "Who is the best actress in Punjabi cinema?",
    "What are the top movies of Samuel L. Jackson?",
    "Who is the most stylish male actor in Bengali cinema?",
    "What is the latest project of Sonakshi Sinha?",
    "Who is the most followed female actor on TikTok?",
    "What is the age of Millie Bobby Brown?"
  ],
  billionaires: [
    "Elon Musk net worth 2025",
    "Richest person in India 2025",
    "How did Jeff Bezos get rich?",
    "Top 10 billionaires under 30",
    "Mukesh Ambani house cost",
    "Billionaires who dropped out",
    "Kylie Jenner business success",
    "Mark Zuckerberg investments",
    "Richest woman in the world",
    "Who is India's youngest billionaire?",
    "Bill Gates philanthropy efforts",
    "Warren Buffet portfolio 2025",
    "Richest tech entrepreneurs",
    "Top billionaires in crypto",
    "Who owns the most land globally?",
    "How many billionaires in India?",
    "Ratan Tata net worth 2025",
    "Gautam Adani rank in Forbes 2025",
    "What businesses do millionaires invest in?",
    "Top 10 self-made billionaires",
    "Who is richer – Elon Musk or Jeff Bezos?",
    "Richest actors in the world",
    "Wealthiest sports personalities",
    "Who are the richest kids?",
    "New billionaires 2025 list",
    "Richest startup founders",
    "Millionaire vs billionaire difference",
    "How many billionaires in US?",
    "Forbes Billionaire List 2025",
    "India's richest families",
    "How to become a millionaire?",
    "Richest fashion designers",
    "Who owns LVMH?",
    "Billionaire divorce settlements",
    "Richest YouTubers 2025",
    "Net worth of Mukesh Ambani's kids",
    "How did Steve Jobs make money?",
    "Celebrity billionaires 2025",
    "Wealthiest countries in 2025",
    "Richest Indian in tech",
    "What is passive income for millionaires?",
    "Richest crypto investors",
    "Bernard Arnault vs Musk",
    "Top billionaire entrepreneurs in AI",
    "Billionaires with no college degree",
    "Who is richer – Ronaldo or Messi?",
    "Highest tax paying billionaire",
    "Richest person in each Indian state",
    "What is net worth vs wealth?",
    "Richest Bollywood producers"
  ],
  cars: [
    "Best electric cars in India 2025",
    "Tesla Model S specs and price",
    "Top 10 cars under 10 lakhs",
    "Upcoming SUVs in India",
    "Most fuel-efficient cars 2025",
    "Hyundai vs Tata – which is better?",
    "Maruti Suzuki latest models",
    "Automatic vs Manual car pros and cons",
    "Mahindra XUV 700 mileage",
    "Most expensive cars in the world",
    "Top 5 safest cars in India",
    "Best family car in 2025",
    "How to choose the right car?",
    "Car insurance tips 2025",
    "Toyota Innova vs Kia Carens",
    "Best hybrid cars 2025",
    "Cheapest electric car in India",
    "Skoda vs Volkswagen",
    "Car loan interest rates 2025",
    "Best resale value cars",
    "Car brands with highest reliability",
    "New car buying guide India",
    "How to maintain a new car?",
    "Difference between SUV and crossover",
    "Top sports cars under 20 lakhs",
    "BMW vs Mercedes comparison",
    "Maruti Fronx features and review",
    "What is ADAS in cars?",
    "Cars with sunroof under 10 lakh",
    "EV vs petrol car – which is better?",
    "Car subscription plans in India",
    "Which car has highest NCAP rating?",
    "Most powerful hatchback 2025",
    "Tata EV cars list",
    "MG Hector vs Tata Harrier",
    "Cars with largest boot space",
    "Best cars for long-distance travel",
    "EV charging stations near me",
    "Honda Elevate reviews",
    "Renault Kiger vs Nissan Magnite",
    "Best automatic cars under 8 lakhs",
    "4x4 vs AWD cars explained",
    "Top CNG cars in India",
    "Fastest accelerating cars 2025",
    "Cars with wireless Android Auto",
    "Best luxury sedan in India",
    "What is the road tax for new cars?",
    "How to register a car in RTO?",
    "Car servicing checklist",
    "Difference between BS6 an"
  ],
  startups: [
    "What is a unicorn startup?",
    "Top 10 startups in India 2025",
    "How to register a startup?",
    "Most funded Indian startups",
    "Shark Tank India funded startups",
    "Startup ideas for students",
    "What is DPIIT recognition?",
    "Startup vs MSME difference",
    "How to raise seed funding?",
    "What is a pitch deck?",
    "Famous Indian startup founders",
    "Best platforms to pitch startup",
    "Incubators vs accelerators",
    "Government schemes for startups",
    "How to get angel investors?",
    "What is product-market fit?",
    "B2B vs B2C startups",
    "What is bootstrapping in business?",
    "What is Series A funding?",
    "Top SaaS startups in India",
    "AI-based startup ideas 2025",
    "EdTech startup trends",
    "FinTech startups in India",
    "Top startup accelerators in India",
    "What is an MVP in startups?",
    "Difference between VC and PE",
    "Valuation methods for startups",
    "What is equity dilution?",
    "Startup India registration steps",
    "Common startup mistakes to avoid",
    "Who is a co-founder?",
    "Top exits in startup ecosystem",
    "Indian startups in Silicon Valley",
    "Role of CTO in a startup",
    "What is a cap table?",
    "Women-led startups in India",
    "Top agri-tech startups",
    "Logistics startups to watch",
    "Startup IPOs in 2025",
    "Social impact startups",
    "Cybersecurity startups 2025",
    "Best books for startup founders",
    "What is burn rate in startups?",
    "How to pivot a startup?",
    "Startup exit strategies",
    "What is vesting in ESOP?",
    "Who regulates startups in India?",
    "Best startup podcasts 2025",
    "Trends in deep tech startups",
    "What is due diligence in funding?"
  ],
  technology: [
    "What is AI and how does it work?",
    "Top programming languages in 2025",
    "What is the metaverse?",
    "How does blockchain work?",
    "Best laptops under ₹50,000",
    "What is quantum computing?",
    "Latest iPhone model 2025",
    "How to secure your online data?",
    "Difference between 4G and 5G",
    "What is ChatGPT used for?",
    "How does machine learning work?",
    "What is cloud computing?",
    "What is an API in programming?",
    "Best Android smartphones 2025",
    "What is a GPU used for?",
    "How does the internet work?",
    "Best coding platforms for beginners",
    "What is cybersecurity?",
    "Role of AI in education",
    "Best budget gaming phones",
    "What is IoT (Internet of Things)?",
    "Difference between frontend and backend",
    "What is GitHub and how to use it?",
    "Smart home gadgets 2025",
    "What is data science?",
    "Tech trends to watch in 2025",
    "What is a VPN and how to use it?",
    "Difference between AI and ML",
    "Top tech companies in India",
    "What is DevOps in IT?",
    "How does facial recognition work?",
    "AR vs VR – What's the difference?",
    "Best online coding courses",
    "Top ethical hacking tools",
    "What is a supercomputer?",
    "How do drones work?",
    "Uses of robotics in industries",
    "Difference between SQL and NoSQL",
    "What is the use of HTML?",
    "Best tech YouTube channels to follow",
    "What is Web3 technology?",
    "Best app development tools",
    "What is SaaS in tech?",
    "How to create a website from scratch?",
    "AI tools for content creation",
    "What is edge computing?",
    "Who invented the internet?",
    "What is the purpose of an OS?",
    "What is the future of AI?",
    "Cybercrimes and how to avoid them"
  ],
  netWorth: [
    "What is the net worth of Elon Musk in 2025?",
    "Shahrukh Khan net worth 2025",
    "Jeff Bezos vs Elon Musk net worth",
    "Net worth of Virat Kohli",
    "Ambani family net worth",
    "Cristiano Ronaldo net worth 2025",
    "Highest-paid actors in Bollywood",
    "Kylie Jenner net worth today",
    "How to calculate personal net worth?",
    "What is Messi's net worth in 2025?",
    "Bill Gates current net worth",
    "Top 10 richest YouTubers in 2025",
    "Net worth of Sundar Pichai",
    "Top richest politicians in India",
    "What is Warren Buffett worth in 2025?",
    "Salman Khan total assets",
    "Net worth of startups after IPO",
    "Who is the richest Indian cricketer?",
    "Net worth of Ratan Tata",
    "Highest-paid Instagram influencers",
    "How to increase your net worth?",
    "Net worth of companies like TCS",
    "Top 5 billionaires in India 2025",
    "What are assets and liabilities?",
    "Difference between gross and net worth",
    "Net worth of Bollywood actresses",
    "Who is the richest actor in Tollywood?",
    "Most valuable companies in 2025",
    "Net worth of Sachin Tendulkar",
    "How to track net worth using Excel?",
    "Net worth of Mukesh Ambani in USD",
    "Most paid CEOs in the world",
    "How often is net worth calculated?",
    "Net worth of Akshay Kumar",
    "Net worth vs salary",
    "Highest-paid athletes in 2025",
    "Net worth of Google founders",
    "Most expensive celebrity homes",
    "Net worth of Indian football players",
    "Monthly income vs net worth",
    "Net worth of Adani Group",
    "How do celebrities make money?",
    "What are intangible assets?",
    "How does Forbes calculate net worth?",
    "Net worth of Bharti Airtel",
    "How net worth changes over time",
    "Net worth of Flipkart after Walmart deal",
    "How to invest for building net worth",
    "Net worth of international singers",
    "Does net worth include home value?"
  ],
  mostSearched: [
    "What is AI?",
    "Trending recipes in 2025",
    "IPL live score today",
    "Top 10 movies on Netflix",
    "Latest tech gadgets 2025",
    "Best travel destinations 2025",
    "iPhone vs Android – which is better?",
    "Symptoms of COVID-25",
    "How to make money online?",
    "Best colleges in India",
    "Today's weather in my location",
    "How to apply for a passport in India?",
    "Current gold rate in India",
    "Best investment options 2025",
    "How to improve English?",
    "Famous quotes by APJ Abdul Kalam",
    "What is global warming?",
    "How to start a business?",
    "Who is the Prime Minister of India?",
    "How to lose weight fast?",
    "Latest Bollywood news",
    "How to file income tax return?",
    "What is cryptocurrency?",
    "What is stock market?",
    "Trending memes today",
    "How to link Aadhaar with PAN?",
    "Most used social media apps",
    "What is ChatGPT used for?",
    "Today's current affairs for exams",
    "Top songs of 2025",
    "What is UPI payment system?",
    "Most searched personalities 2025",
    "How to crack UPSC exam?",
    "Top tourist places in India",
    "How to create a resume?",
    "What is GDP of India 2025?",
    "How to get fit at home?",
    "Most popular baby names 2025",
    "How to check exam results?",
    "Viral YouTube videos today",
    "How to get scholarship for college?",
    "Famous motivational speakers",
    "What is inflation?",
    "Best online shopping apps",
    "How to open a bank account?",
    "How to prepare for board exams?",
    "What is GDP vs GNP?",
    "Easy home workouts",
    "How to buy shares in India?",
    "What is the meaning of life?"
  ]
};

/**
 * Get sentence suggestions based on input text
 * @param input User input text
 * @returns Promise with array of suggestions
 */
export const getSuggestions = async (input: string): Promise<string[]> => {
  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 200 + Math.random() * 200));
  
  const cleanInput = input.trim().toLowerCase();
  if (!cleanInput) return [];
  
  // Combine all suggestions into one array
  const allSuggestions = Object.values(suggestions).flat();
  
  // Filter suggestions that match the input
  const matches = allSuggestions.filter(suggestion => 
    suggestion.toLowerCase().includes(cleanInput)
  );
  
  // Sort matches by relevance (exact matches first, then starts with, then includes)
  const sortedMatches = matches.sort((a, b) => {
    const aLower = a.toLowerCase();
    const bLower = b.toLowerCase();
    
    if (aLower === cleanInput) return -1;
    if (bLower === cleanInput) return 1;
    
    if (aLower.startsWith(cleanInput)) return -1;
    if (bLower.startsWith(cleanInput)) return 1;
    
    return 0;
  });
  
  // Return top 5 matches
  return sortedMatches.slice(0, 5);
};